name: Cache

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: macos-12
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Setup environment
      run: |
        brew update --preinstall
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/mint.rb" >> .github/brew-formulae
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/xcbeautify.rb" >> .github/brew-formulae
        sudo xcode-select -s /Applications/Xcode_14.2.app

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.mint
          ~/Library/Caches/Homebrew/mint--*
          ~/Library/Caches/Homebrew/downloads/*--mint-*
          ~/Library/Caches/Homebrew/xcbeautify--*
          ~/Library/Caches/Homebrew/downloads/*--xcbeautify-*
          ~/.npm
          DJSystemiOS-PRLinter/.build
        key: ${{ runner.os }}-deps-${{ hashFiles('**/Mintfile', '**/package-lock.json', '**/Package.resolved', '.github/brew-formulae') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    - name: Install dependencies
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install mint xcbeautify
        make mint
        npm install -g danger
        cd DJSystemiOS-PRLinter && swift build -c release

